### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Demarsch** [Demarsch/self-driving-car-sim#1]
- [ ] create a scene with physical bounds
- [ ] create a car a make it accelerate, decelerate and turn
- [ ] using ray-casting imitate a car FoV
- [ ] establish car communication with the environment in the form of action-state-reward
- [ ] design and implement one of the reinforcement learning techniques
- [ ] train the agent until it learns to avoid the obstacles
- [ ] add extra visuals: car FoV, closest obstacle detector (line from car to obstacle - the closer the more thick and red it becomes, floating numbers - rewards and penalties)
- [ ] add configuration elements: level selector, obstacle adder, settings (e.g. penalty-reward ratio for specific actions)
